### PR TITLE
8275703: System.loadLibrary fails on Big Sur for libraries hidden from filesystem

### PR DESCRIPTION
**Pull request by omikhaltsova**
I'd like to backport JDK-8275703 to jdk15u in order to fix the same issue.
The patch applies almost cleanly except NativeLibraries.java due to the copyright year and the import section differences.
The issue was reproduced and verified locally on macOS Monterey 12.0.1 according to the guideline described in the bug. After applying this patch the issue was eliminated.
Tested with tier1 (macOS x64, Linux x64, Windows x64).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8275703](https://bugs.openjdk.org/browse/JDK-8275703): System.loadLibrary fails on Big Sur for libraries hidden from filesystem

### Reviewers
 * [Vladimir Kempik](https://openjdk.org/census#vkempik) (@VladimirKempik - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk15u-dev pull/222/head:pull/222` \
`$ git checkout pull/222`

Update a local copy of the PR: \
`$ git checkout pull/222` \
`$ git pull https://git.openjdk.org/jdk15u-dev pull/222/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 222`

View PR using the GUI difftool: \
`$ git pr show -t 222`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk15u-dev/pull/222.diff">https://git.openjdk.org/jdk15u-dev/pull/222.diff</a>

</details>

### CODE REVIEW

**Comment by VladimirKempik** [comment]
so, this is to load libraries which are not present on disk but present in dyld cache, right ?

**Review by VladimirKempik — APPROVED** [review]
lgtm

**Comment by omikhaltsova** [comment]
exactly, the fix is for macOS 11+, for libraries loaded from the dynamic linker cache.

**Pull request closed without merging**
