### PR TITLE
8186670: Implement _onSpinWait() intrinsic for AArch64

### PR DESCRIPTION
**Pull request by eastig**
A backport of a configurable implementation of _onSpinWait() intrinsic to achieve parity with x86 which has it implemented.
The risk of changes is low. By default it is off.
Tested for fastdebug and release builds:

- `gtest`: Passed
- `tier1`...`tier3`: Passed except [JDK-8261534](https://bugs.openjdk.java.net/browse/JDK-8261534) and [JDK-8277488](https://bugs.openjdk.java.net/browse/JDK-8277488)
- `hotspot/jtreg/compiler/onSpinWait`: Passed

Applying the patch had issues to find proper positions. No code changes are needed after repositioning.
Changes to `globals_aarch64.hpp` needed the new added options definitions to be converted from the new format to the old one. `vm.flagless` was removed from the new tests. 
Changes to `vm_version_aarch64.cpp`, instantiation of `SpinWait`, use C++11 syntax. They needed to be changed to C++03 syntax.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issues
 * [JDK-8186670](https://bugs.openjdk.java.net/browse/JDK-8186670): Implement _onSpinWait() intrinsic for AArch64
 * [JDK-8274564](https://bugs.openjdk.java.net/browse/JDK-8274564): Add diagnostic VM options to control Thread.onSpinWait intrinsic code for AArch64 (**CSR**)

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk15u-dev pull/181/head:pull/181` \
`$ git checkout pull/181`

Update a local copy of the PR: \
`$ git checkout pull/181` \
`$ git pull https://git.openjdk.java.net/jdk15u-dev pull/181/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 181`

View PR using the GUI difftool: \
`$ git pr show -t 181`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk15u-dev/pull/181.diff">https://git.openjdk.java.net/jdk15u-dev/pull/181.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — COMMENTED** [review]
Lgtm, except:

I don't see any C++03 vs C++11 differences in vm_version_aarch64.cpp. What am I missing?

Do [JDK-8261534](https://bugs.openjdk.java.net/browse/JDK-8261534) and [JDK-8277488](https://bugs.openjdk.java.net/browse/JDK-8277488) also fail without this patch?

**Comment by eastig** [comment]
> Lgtm, except:
> 
> I don't see any C++03 vs C++11 differences in vm_version_aarch64.cpp. What am I missing?

C++11 `return SpinWait{}` vs C++03 `return SpinWait();`

> 
> Do [JDK-8261534](https://bugs.openjdk.java.net/browse/JDK-8261534) and [JDK-8277488](https://bugs.openjdk.java.net/browse/JDK-8277488) also fail without this patch?

Yes, they do.

**Review by phohensee — APPROVED** [review]
I skipped right over the {} vs ()!

Lgtm.

**Comment by theRealAph** [comment]
I'm not sure about this one. With OnSpinWaitInst=isb, ThreadOnSpinWaitProducerConsumer gets better but ThreadOnSpinWaitSharedCounter gets worse. So there are cases where it's worth using, but does this patch meet the "enhancement that provides substantial benefit to OpenJDK 11u users and it is of low risk" requirement? I guess as long as the default for all platforms stays at "off" it won't cause any regressions.
Do you know of any applications that substantially benefit?

**Comment by eastig** [comment]
> So there are cases where it's worth using, but does this patch meet the "enhancement that provides substantial benefit to OpenJDK 11u users and it is of low risk" requirement?

This is for 15u not for 11u.

> Do you know of any applications that substantially benefit?

Yes, we have services which got improvements. Also 15u version of `java.util.concurrent.SynchronousQueue` uses `Thread.onSpinWait`. A SynchronousQueue microbenchmark (see it in https://bugs.openjdk.java.net/browse/JDK-8267502) got the following geomean ops/s when ran on 2 CPUs 60 times:
- No intrinsic implementation: 226,732.8 ops/s
- One ISB implementation: 1,996,916.3 ops/s

The difference is 8.8x.

**Comment by eastig** [comment]
> Interesting, so I guess that's much more dramatic than anything we have in
> the OpenJDK benchmarks. Maybe we want a JMH version of that.

I've converted it to the JMH version. Results:
```
No intrinsic:
Benchmark                                 Mode  Cnt     Score     Error  Units
ThreadOnSpinWaitProducerConsumer01.trial  avgt   10  2078.777 ± 743.187  ms/op

1-ISB
Benchmark                                 Mode  Cnt    Score   Error  Units
ThreadOnSpinWaitProducerConsumer01.trial  avgt   10  239.728 ± 3.207  ms/op
```

> Do you think that onSpinWait() = ISB would help with 8267502?

Maybe, if I knew more details of https://bugs.openjdk.java.net/browse/JDK-8246677.

**Pull request closed without merging**
