### PR TITLE
8297804: (tz) Update Timezone Data to 2022g

### PR DESCRIPTION
**Pull request by gnu-andrew**
Clean backport of the latest tzdata update.

This pull request contains a backport of commit [ce896731](https://github.com/openjdk/jdk/commit/ce896731d38866c2bf99cd49525062e150d94160) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Andrew John Hughes on 7 Dec 2022 and was reviewed by Naoto Sato.

Tests in java/util/TimeZone, java/time/test, sun/util/calendar, sun/util/resources and sun/text/resources all pass.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297804](https://bugs.openjdk.org/browse/JDK-8297804): (tz) Update Timezone Data to 2022g

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk15u-dev pull/317/head:pull/317` \
`$ git checkout pull/317`

Update a local copy of the PR: \
`$ git checkout pull/317` \
`$ git pull https://git.openjdk.org/jdk15u-dev pull/317/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 317`

View PR using the GUI difftool: \
`$ git pr show -t 317`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk15u-dev/pull/317.diff">https://git.openjdk.org/jdk15u-dev/pull/317.diff</a>

</details>

### CODE REVIEW

**Comment by yan-too** [comment]
Thank you, @gnu-andrew ! Marked jdk15u-fix-yes. Sorry I was away for a week. Hope you will integrate before Dec 21-th; otherwise we'll change repository to jdk15u and label to critical.

**Comment by gnu-andrew** [comment]
> Thank you, @gnu-andrew ! Marked jdk15u-fix-yes. Sorry I was away for a week. Hope you will integrate before Dec 21-th; otherwise we'll change repository to jdk15u and label to critical.

No worries and thanks for the approval. I'll integrate now.

I also have 13u in the pipeline. Should I target that to jdk13u or is there still time to get it in via jdk13u-dev? Should have a PR ready in the next few hours.

**Comment by gnu-andrew** [comment]
> > Thank you, @gnu-andrew ! Marked jdk15u-fix-yes. Sorry I was away for a week. Hope you will integrate before Dec 21-th; otherwise we'll change repository to jdk15u and label to critical.
> 
> No worries and thanks for the approval. I'll integrate now.
> 
> I also have 13u in the pipeline. Should I target that to jdk13u or is there still time to get it in via jdk13u-dev? Should have a PR ready in the next few hours.

13u: https://github.com/openjdk/jdk13u-dev/pull/444

**Pull request closed without merging**
